### ISSUE TITLE
Just saying hi

### ISSUE THREAD

**Issue by peterdemin** [ditrit/specimen#1]
Hi @mathieucaroff and @mcaroff-wallix, I found this repo accidentally, and I like the idea.
I would love to learn more about your vision, and also want to share mine.
I started jamming on the checkpoint framework a couple of weeks ago: https://peter.demin.dev/15_projects/01-checkpoint-framework.html.
Unfortunately, the "checkpoint" name was taken many times, so when it came to implementation I had to pick something else, so I started [i8t (introspect)](https://github.com/peterdemin/i8t) - a Python project that allows instrumenting both test and runtime to collect specimen data, and use it as both test inputs/expected outputs and mocks.
Ultimately, I want to expand to Golang and Javascript.
Let me know if you'd be interested to connect, and what is the best communication channel.

**Comment by mathieucaroff** [comment]
Hi Peter, I'm glad you like the concept of the Specimen repository. I guess that if you are going to implement i8t in multiple languages, you might want to write part of your tests using Specimen to avoid duplicating the test data. Let me know if you encounter any issue while getting started with Specimen: the library could use some more documentation.

If you want to connect with me, my discord name is mathieuc.
